
enclaves:
  - name: sgx-hashmachine
    build:
      builder: docker
      build_kwargs:
        context_path: .
        file: nix.Dockerfile
        target: export-stage
      output_dir: out
      enclave_file: Enclave.so
    enclave_config: Enclave/Enclave.config.xml
    #signed_enclave:
    #  path: .enclavehub/Enclave.signed.so
    #  mrenclave: a8a3094d76217c5dd0a1126ac142b36dd34f88514a99bf8dfc8ea852f1fa6238 
    #  mrsigner: 5c428b3e21b898d06ae06bca549f107d4a12d6bbde3013a86622a344073b9134
    #ias_reports:
    #  - .enclavehub/ias-report.json
